Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Models/Dealers/DealerDetailsOutputModel.cs
namespace CarRentalSystem.Admin.Models.Dealers
{
    public class DealerDetailsOutputModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string PhoneNumber { get; set; }

        public int TotalCarAds { get; private set; }
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Models/Dealers/DealerFormModel.cs
namespace CarRentalSystem.Admin.Models.Dealers
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using CarRentalSystem.Models;

    public class DealerFormModel : IMapFrom<DealerDetailsOutputModel>
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Models/Dealers/DealerInputModel.cs
namespace CarRentalSystem.Admin.Models.Dealers
{
    using CarRentalSystem.Models;

    public class DealerInputModel : IMapFrom<DealerFormModel>
    {
        public string Name { get; set; }

        public string PhoneNumber { get; set; }
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Models/ErrorViewModel.cs
namespace CarRentalSystem.Admin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Models/Statistics/StatisticsOutputModel.cs
namespace CarRentalSystem.Admin.Models.Statistics
{
    public class StatisticsOutputModel
    {
        public int TotalCarAds { get; set; }

        public int TotalRentedCars { get; set; }
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Controllers/AdministrationController.cs
namespace CarRentalSystem.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using CarRentalSystem.Infrastructure;
    using Infrastructure;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using Refit;

    [AuthorizeAdministrator]
    public abstract class AdministrationController : Controller
    {
        protected async Task<ActionResult> Handle(Func<Task> action, ActionResult success, ActionResult failure)
        {
            try
            { 
                await action();
                return success;
            }
            catch (ApiException exception)
            {
                this.ProcessErrors(exception);
                return failure;
            }
        }

        private void ProcessErrors(ApiException exception)
        {
            if (exception.HasContent)
            {
                JsonConvert
                    .DeserializeObject<List<string>>(exception.Content)
                    .ForEach(error => this.ModelState.AddModelError(string.Empty, error));
            }
            else
            {
                this.ModelState.AddModelError(string.Empty, "Internal server error.");
            }
        }
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Controllers/DealersController.cs
namespace CarRentalSystem.Admin.Controllers
{
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Models.Dealers;
    using Services.Dealers;

    public class DealersController : AdministrationController
    {
        private readonly IDealersService dealers;
        private readonly IMapper mapper;

        public DealersController(IDealersService dealers, IMapper mapper)
        {
            this.dealers = dealers;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
            => View(await this.dealers.All());

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var dealer = await this.dealers.Details(id);

            var dealerForm = this.mapper.Map<DealerFormModel>(dealer);

            return View(dealerForm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, DealerFormModel model) 
            => await this.Handle(
                async () => await this.dealers
                    .Edit(id, this.mapper.Map<DealerInputModel>(model)),
                success: RedirectToAction(nameof(Index)),
                failure: View(model));
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Controllers/HomeController.cs
namespace CarRentalSystem.Admin.Controllers
{
    using System.Diagnostics;
    using CarRentalSystem.Infrastructure;
    using Infrastructure;
    using Microsoft.AspNetCore.Mvc;
    using Models;

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            if (this.User.IsAdministrator())
            {
                return this.RedirectToAction(nameof(StatisticsController.Index), "Statistics");
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() 
            => View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier
            });
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Controllers/IdentityController.cs
namespace CarRentalSystem.Admin.Controllers
{
    using System;
    using System.Threading.Tasks;
    using AutoMapper;
    using CarRentalSystem.Infrastructure;
    using Infrastructure;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Models.Identity;
    using Services.Identity;

    using static CarRentalSystem.Infrastructure.InfrastructureConstants;

    public class IdentityController : AdministrationController
    {
        private readonly IIdentityService identityService;
        private readonly IMapper mapper;

        public IdentityController(
            IIdentityService identityService,
            IMapper mapper)
        {
            this.identityService = identityService;
            this.mapper = mapper;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginFormModel model)
            => await this.Handle(
                async () =>
                {
                    var result = await this.identityService
                        .Login(this.mapper.Map<UserInputModel>(model));

                    this.Response.Cookies.Append(
                        AuthenticationCookieName,
                        result.Token,
                        new CookieOptions
                        {
                            HttpOnly = true,
                            Secure = true,
                            MaxAge = TimeSpan.FromDays(1)
                        });
                },
                success: RedirectToAction(nameof(StatisticsController.Index), "Statistics"),
                failure: View("../Home/Index", model));

        [AuthorizeAdministrator]
        public IActionResult Logout()
        {
            this.Response.Cookies.Delete(AuthenticationCookieName);

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Controllers/StatisticsController.cs
namespace CarRentalSystem.Admin.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Services.Statistics;

    public class StatisticsController : AdministrationController
    {
        private readonly IStatisticsService statistics;

        public StatisticsController(IStatisticsService statistics) 
            => this.statistics = statistics;

        public async Task<IActionResult> Index()
            => View(await this.statistics.Full());
    }
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Views/Home/Index.cshtml
@model LoginFormModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <h2>Login</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <form asp-controller="Identity" asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Code It Up/TV/Eventual Consistency Done Right/CarRentalSystem.Admin/Views/Shared/_Layout.cshtml
@using CarRentalSystem.Infrastructure
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Rental System Administration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (this.User.IsAdministrator())
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Statistics" asp-action="Index">Car Rental System Administration</a>
                    <a class="float-left" asp-area="" asp-controller="Dealers" asp-action="Index">Dealers</a>
                    <a class="float-right" asp-area="" asp-controller="Identity" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Car Rental System Administration</a>
                }

                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Car Rental System
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>